apiVersion: apps/v1
kind: Deployment
metadata:
  name: processing-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: processing-worker
  template:
    metadata:
      labels:
        app: processing-worker
    spec:
      containers:
        - name: processing-worker
          image: acrspeechtocode.azurecr.io/worker:latest
          resources:
            requests:
              cpu: "2"
              memory: "16Gi"
            limits:
              cpu: "3"
              memory: "24Gi"
      tolerations:
        - key: "workload"
          operator: "Equal"
          value: "processing"
          effect: "NoSchedule"
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: processing-worker-scaler
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: processing-worker
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 70
