apiVersion: apps/v1
kind: Deployment
metadata:
  name: processing-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: processing-worker
  template:
    metadata:
      labels:
        app: processing-worker
    spec:
      containers:
        - name: processing-worker
          image: acrspeechtocode.azurecr.io/worker:2ce55859435a6b19d509cef9d0154ac34f8cd707
          resources:
            requests:
              cpu: "2"
              memory: "16Gi"
            limits:
              cpu: "3"
              memory: "24Gi"
      tolerations:
        - key: "workload"
          operator: "Equal"
          value: "processing"
          effect: "NoSchedule"
