apiVersion: apps/v1
kind: Deployment
metadata:
  name: speech-to-code
spec:
  replicas: 1
  selector:
    matchLabels:
      app: speech-to-code
  template:
    metadata:
      labels:
        app: speech-to-code
    spec:
      containers:
        - name: speech-to-code
          image: acrspeechtocode.azurecr.io/api:0d582880d2beba9bf0ce75bec8e0b2dcae8023f0
          ports:
            - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: speech-to-code-service
spec:
  selector:
    app: speech-to-code
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: speech-to-code-ingress
spec:
  rules:
    - http:
        paths:
          - path: /speech-to-code
            pathType: Prefix
            backend:
              service:
                name: speech-to-code-service
                port:
                  number: 80
